# Generated by Django 5.1.1 on 2025-09-15 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='e_branch',
            field=models.CharField(choices=[('Frontend Devloper', 'Frontend Devloper'), ('Backend Devloper', 'Backend Devloper'), ('Tester', 'Tester')], default='Backend Devloper', max_length=50),
        ),
    ]
