# Generated by Django 5.1.1 on 2025-09-24 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_alter_employee_e_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='contactus_images'),
        ),
        migrations.AddField(
            model_name='employee',
            name='e_img',
            field=models.ImageField(blank=True, null=True, upload_to='employe_images'),
        ),
    ]
