# Generated by Django 5.1.1 on 2025-09-16 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_alter_employee_e_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='e_branch',
            field=models.CharField(choices=[('Frontend Devloper', 'Frontend Devloper'), ('Backend Devloper', 'Backend Devloper'), ('Tester', 'Tester'), ('Full-Stack Devloper', 'Full-Stack Devloper')], default='Backend Devloper', max_length=50),
        ),
    ]
