# Generated by Django 5.0 on 2024-03-04 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='myimage',
            field=models.ImageField(blank=True, null=True, upload_to='userprofile'),
        ),
    ]
